"""Helper script to install pre-commit and commit-msg hooks into .git/hooks/."""
from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

def install() -> None:
    hooks_dir = Path(__file__).resolve().parent.parent / ".git" / "hooks"
    if not hooks_dir.exists():
        print("Error: .git/hooks directory not found. Please run this in the project root.", file=sys.stderr)
        sys.exit(1)

    pre_commit_content = """#!/bin/sh
# Auto-generated by install_hooks.py
python .hooks/bump_version.py
git add src/famicent/__init__.py
"""

    commit_msg_content = """#!/bin/sh
# Auto-generated by install_hooks.py
python .hooks/bump_version.py --no-bump "$1"
"""

    pre_commit_path = hooks_dir / "pre-commit"
    commit_msg_path = hooks_dir / "commit-msg"

    pre_commit_path.write_text(pre_commit_content, encoding="utf-8")
    commit_msg_path.write_text(commit_msg_content, encoding="utf-8")

    # Set executable permissions
    for p in (pre_commit_path, commit_msg_path):
        current_mode = os.stat(p).st_mode
        os.chmod(p, current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print("Git hooks installed successfully!")

if __name__ == "__main__":
    install()
